<?php

return [
    'table_name' => 'accessories',

    'drop_scheme' => "SET FOREIGN_KEY_CHECKS = 0; DROP TABLE IF EXISTS `accessories`; SET FOREIGN_KEY_CHECKS = 1",

    'scheme' => "CREATE TABLE IF NOT EXISTS `accessories` (
        `id` int(11) NOT NULL AUTO_INCREMENT,
        `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `category` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `Subcategory` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `description` TEXT,
        `price` decimal(6,2),
        `stock` int(11),
        `created_at` timestamp NOT NULL,
        `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
        `deleted_at` timestamp DEFAULT NULL,
        `created_by` int(11) NOT NULL,
        `updated_by` int(11),
        `deleted_by` int(11),
        PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;",

    'relations' => [
        'ALTER TABLE `accessories` ADD FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `accessories` ADD FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `accessories` ADD FOREIGN KEY (`deleted_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
    ],

    'seeder' => [
        'type' => 'array',
        'data' => array(
            
            [
                'id'            => 30,
                'name'          => 'Sigaarhouder leer met sigaarknipper',
                'image'         => 'sigaarhouder1.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCase',
                'description'   => 'lorem',
                'price'         => 29.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 31,
                'name'          => 'Sigaarhouder hout',
                'image'         => 'sigaarhouder2.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCase',
                'description'   => 'lorem',
                'price'         => 25.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 32,
                'name'          => 'Sigaarhouder leder met sigaarknipper',
                'image'         => 'sigaarhouder3.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCase',
                'description'   => 'lorem',
                'price'         => 19.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 33,
                'name'          => 'Sigaarknipper',
                'image'         => 'sigaarknipper1.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCutter',
                'description'   => 'lorem',
                'price'         => 9.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 34,
                'name'          => 'Sigaarknipper schaarvorm',
                'image'         => 'sigaarknipper2.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCutter',
                'description'   => 'lorem',
                'price'         => 9.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 35,
                'name'          => 'Sigaarknipper standaard',
                'image'         => 'sigaarknipper3.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCutter',
                'description'   => 'lorem',
                'price'         => 8.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 36,
                'name'          => 'Sigaarknipper luxe',
                'image'         => 'sigaarknipper4.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCutter',
                'description'   => 'lorem',
                'price'         => 19.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 37,
                'name'          => 'Sigaarknipper goud/carbon',
                'image'         => 'sigaarknipper5.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCutter',
                'description'   => 'lorem',
                'price'         => 19.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 38,
                'name'          => 'Sigaarknipper deluxe',
                'image'         => 'sigaarknipper6.jpg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCutter',
                'description'   => 'lorem',
                'price'         => 14.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 39,
                'name'          => 'Sigaarknipper hand',
                'image'         => 'sigaarknipper7.jpg',
                'category'      => 'accessories',
                'Subcategory'   => 'cigarCutter',
                'description'   => 'lorem',
                'price'         => 9.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 40,
                'name'          => 'Aansterker deluxe',
                'image'         => 'aansteker2.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'lighter',
                'description'   => 'lorem',
                'price'         => 17.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 41,
                'name'          => 'Aansteker stormbestendig',
                'image'         => 'aansteker3.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'lighter',
                'description'   => 'lorem',
                'price'         => 12.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 42,
                'name'          => 'Aansteker 3 vlams',
                'image'         => 'aansteker4.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'lighter',
                'description'   => 'lorem',
                'price'         => 14.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 43,
                'name'          => 'Asbak ovaal',
                'image'         => 'asbak2.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'ashtray',
                'description'   => 'lorem',
                'price'         => 12.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 44,
                'name'          => 'Asbak hout en uitschuifbaar',
                'image'         => 'asbak3.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'ashtray',
                'description'   => 'lorem',
                'price'         => 18.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 45,
                'name'          => 'Asbak tafelmodel',
                'image'         => 'asbak4.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'ashtray',
                'description'   => 'lorem',
                'price'         => 29.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 46,
                'name'          => 'Asbak alu. inc. houder',
                'image'         => 'asbak5.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'ashtray',
                'description'   => 'lorem',
                'price'         => 24.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 47,
                'name'          => 'Asbak inc. houder',
                'image'         => 'asbak6.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'ashtray',
                'description'   => 'lorem',
                'price'         => 17.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 48,
                'name'          => 'Asbak luxe',
                'image'         => 'asbak7.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'ashtray',
                'description'   => 'lorem',
                'price'         => 29.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],

            [
                'id'            => 49,
                'name'          => 'Asbak Montecristo de luxe',
                'image'         => 'asbak8.jpeg',
                'category'      => 'accessories',
                'Subcategory'   => 'ashtray',
                'description'   => 'lorem',
                'price'         => 29.95,
                'stock'         => 20,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            
        ),
    ]
];